---
- import_playbook: flatpak/base.yml
- import_playbook: vscode-extensions.yml

- name: Complete DX Environment Setup
  hosts: localhost
  connection: local

  tasks:
    - name: "🎉 Complete setup finished"
      debug:
        msg: |
          ✅ Complete DX Environment Setup Finished!

          📱 Applications installed via Flatpak
          📁 Development directories created
          🔌 VSCode extensions configured
          🐚 Shell aliases added

          💡 Restart your terminal to use new aliases
          🚀 Your development environment is ready!
