---
- name: DX Development Environment Setup
  hosts: localhost
  connection: local

  vars:
    vscode_extensions:
    - bradlc.vscode-tailwindcss

  tasks:
    - name: "🔍 Check if VSCode is installed"
      command: which code
      register: vscode_check
      failed_when: false
      changed_when: false
    
    - name: "Install VSCode extensions"
      shell: "code --install-extension {{ item }}"
      loop: "{{ vscode_extensions }}"
      when: vscode_check.rc == 0
      register: extension_results
      failed_when: extension_results.rc != 0 and "already installed" not in extension_results.stderr
      changed_when: "'successfully installed' in extension_results.stdout"

    - name: "Setup Summary"
      debug:
        msg: |
          ✅ DX Environment Setup Complete!
          
          🔌 Configured VSCode with {{ vscode_extensions | length }} extensions  
          💡 You may need to restart your terminal to see the new aliases
          🚀 Happy coding!